"""empty message

Revision ID: 08a58f1979de
Revises: f877fc8f42a7
Create Date: 2017-09-14 17:23:15.722340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a58f1979de'
down_revision = 'f877fc8f42a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('day_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'days', ['day_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'day_id')
    # ### end Alembic commands ###
