"""empty message

Revision ID: 09b375755245
Revises: 60c31e22d934
Create Date: 2017-09-15 05:47:30.766263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b375755245'
down_revision = '60c31e22d934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'body_html')
    # ### end Alembic commands ###
