"""empty message

Revision ID: 18941b21111b
Revises: 
Create Date: 2017-09-14 17:13:48.704161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18941b21111b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_topic', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_title', sa.String(length=250), nullable=True),
    sa.Column('lesson_content', sa.String(), nullable=True),
    sa.Column('lesson_day', sa.String(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('weeks')
    # ### end Alembic commands ###
