"""empty message

Revision ID: 60c31e22d934
Revises: 07bf478d5cd9
Create Date: 2017-09-15 04:46:05.892425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c31e22d934'
down_revision = '07bf478d5cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('body', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('day_number', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('lessons', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('week_number', sa.Integer(), nullable=True))
    op.drop_column('lessons', 'title')
    op.drop_column('lessons', 'day')
    op.drop_column('lessons', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'week_number')
    op.drop_column('lessons', 'lessons')
    op.drop_column('lessons', 'day_number')
    op.drop_column('lessons', 'body')
    # ### end Alembic commands ###
