"""empty message

Revision ID: cf6293e7f31a
Revises: c0657a89ab14
Create Date: 2017-09-15 10:30:30.994580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6293e7f31a'
down_revision = 'c0657a89ab14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
